# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Wireless Corne'
on: push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      clipboard: '["win"]'
      nav: '["invertedt"]'
      alphas: '["qwerty"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1\nCONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7\nCONFIG_ZMK_KEYBOARD_NAME=\"FabW Corne Kb\""]'
