# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My New Wireless Corne'
on: push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["eyelash_corne_left", "eyelash_corne_right"]'
      shield: '["nice_oled"]'
      modules: '["RodolpheFouquet/ergo-keyboard-config/main"]'
      nav: '["invertedt"]'
      alphas: '["qwerty"]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
